# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heavylift_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 8080

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
